---
name: CI for pipeline code

on:
  push:
    paths:
      - .github/
    branches:
      - main
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
  workflow_call:

jobs:
  lint_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mega Lint code base
        uses: oxsecurity/megalinter/flavors/ci_light@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          GITHUB_WORKSPACE: .github
          EXCLUDED_DIRECTORIES: library,node_modules,resources,.rm,.env,.cicd,.pre-commit-config.yaml