---
name: "Generate new release"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci-workflow:
    uses: ./.github/workflows/ci_workflow.yml
  release:
    name: Generate new release
    needs: [ci-workflow]
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.2.0
        id: semantic_release
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
            @semantic-release/commit-analyzer
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    secrets: inherit